stop_at_error: False
timing: True

likelihood:
  lsst_y1.lsst_3x2pt:
    path: ./external_modules/data/lsst_y1

prior:
  external: "lambda omegabh2, H0: np.log(0.03 <= omegabh2/((H0/100)**2) <= 0.07)"
  external: "lambda omegach2, H0: np.log(0.01 <= omegach2/((H0/100)**2) <= 0.9)"

params:
  logA:
    prior:
      min: 1.61
      max: 3.91
    ref:
      dist: norm
      loc: 3.0675
      scale: 0.005
    proposal: 0.005
    latex: \log(10^{10} A_\mathrm{s})
    drop: true
  As:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.97
      scale: 0.003
    proposal: 0.003
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 69.0
      scale: 0.3
    proposal: 0.3
    latex: H_0
  omegabh2:
    prior:
      min: 0.01
      max: 0.04
    ref:
      dist: norm
      loc: 0.0228528
      scale: 0.001
    proposal: 0.001
    latex: \Omega_\mathrm{b} h^2
  omegach2:
    prior:
      min: 0.001
      max: 0.99
    ref:
      dist: norm
      loc: 0.1199772
      scale: 0.001
    proposal: 0.001
    latex: \Omega_\mathrm{c} h^2
  mnu:
    value: 0.06
  tau:
    value: 0.0543
    latex: \tau_\mathrm{reio}
  omegal:
    latex: \Omega_\Lambda
  omegam:
    latex: \Omega_\mathrm{m}
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  omegab:
    derived: 'lambda omegabh2, H0: omegabh2/((H0/100)**2)'
    latex: \Omega_\mathrm{b}
  omegac:
    derived: 'lambda omegach2, H0: omegach2/((H0/100)**2)'
    latex: \Omega_\mathrm{c}
  sigma8:
    latex: \sigma_8
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  A:
    derived: 'lambda As: 1e9*As'
    latex: 10^9 A_\mathrm{s}
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
  rdrag:
    latex: r_\mathrm{drag}
  yheused:
    latex: Y_P^\mathrm{BBN}
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  zstar:
    latex: z_*
  rstar:
    latex: r_*
  thetastar:
    latex: 100\theta_*
  DAstar:
    latex: D_\mathrm{A}/\mathrm{Gpc}
  zdrag:
    latex: z_\mathrm{drag}
  kd:
    latex: k_\mathrm{D}
  thetad:
    latex: 100\theta_\mathrm{D}
  zeq:
    latex: z_\mathrm{eq}
  keq:
    latex: k_\mathrm{eq}
  thetaeq:
    latex: 100\theta_\mathrm{eq}
  thetarseq:
    latex: 100\theta_\mathrm{s,eq}
  DHBBN:
    derived: "lambda DH: 10**5*DH"
    latex: 10^5 \mathrm{D}/\mathrm{H}
  zrei:
    latex: z_\mathrm{re}
  nrun:
    value: 0.0
    latex: n_\mathrm{run}
  nrunrun:
    value: 0.0
    latex: n_\mathrm{run,run}
  omegak:
    value: 0.0
    latex: \Omega_k

theory:
  camb:
    path: ./external_modules/code/CAMB
    use_renames: True
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.15
      lens_potential_accuracy: 1.1
      num_massive_neutrinos: 1
      nnu: 3.046
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 20

sampler:
  mcmc:
    # ---------------------------------------------------------------------
    # File (w/ path) or matrix defining a covariance matrix for the proposal:
    # - null (default): will be generated from params info (prior and proposal)
    # - matrix: remember to set `covmat_params` to the parameters in the matrix
    covmat:
    covmat_params:
    # --------------------------------------
    # --------------------------------------
    # Proposal covariance matrix learning
    # --------------------------------------
    # --------------------------------------
    learn_proposal: True
    # Don't learn if convergence better than...
    learn_proposal_Rminus1_min: 0.1
    # --------------------------------------
    # --------------------------------------
    # Convergence and stopping
    # --------------------------------------
    # --------------------------------------
    # Maximum number of posterior evaluations
    max_samples: .inf
    # Gelman-Rubin R-1 on means
    Rminus1_stop: 0.02
    # Gelman-Rubin R-1 on std deviations
    Rminus1_cl_stop: 0.2
    Rminus1_cl_level: 0.95
    # --------------------------------------
    # --------------------------------------
    # Exploiting speed hierarchy
    # --------------------------------------
    # --------------------------------------
    measure_speeds: False
    drag: False
    blocking:
      - [1,
          [
            logA, ns, H0, omegabh2, omegach2
          ]
        ]
      - [4,
          [
            LSST_DZ_S1, LSST_DZ_S2, LSST_DZ_S3, LSST_DZ_S4, LSST_DZ_S5, 
            LSST_A1_1, LSST_A1_2,
            LSST_DZ_L1, LSST_DZ_L2, LSST_DZ_L3, LSST_DZ_L4, LSST_DZ_L5
          ]
        ]
      - [25,
          [
            LSST_M1, LSST_M2, LSST_M3, LSST_M4, LSST_M5,
            LSST_B1_1, LSST_B1_2, LSST_B1_3, LSST_B1_4, LSST_B1_5,
            LSST_BARYON_Q1, LSST_BARYON_Q2
          ]
        ]
    oversample_power: 0
    oversample_thin: True
    # --------------------------------------
    # --------------------------------------
    # Avoid chain getting suck forever
    # --------------------------------------
    # --------------------------------------
    max_tries: 10000
    burn_in: 0
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    # When no MPI used, number of fractions of the chain to compare
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    Rminus1_single_split: 4

output: ./projects/lsst_y1/chains/mcmc_w_baryons/mcmc_w_baryons_exp
